import type { Metadata } from "next";
import { type PropsWithChildren } from "react";
import MainLayoutHeader from "./_components/layout/Header";
import MainLayoutFooter from "./_components/layout/Footer";
import CheckoutManager from "./_components/layout/CheckoutManager";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// authOptions

export default function RootLayout(props: PropsWithChildren) {
  return (
    <>
      <MainLayoutHeader />
      <main className="mt-main-header-h max-w-main mx-auto flex w-full flex-grow flex-col">
        {props.children}
      </main>
      <MainLayoutFooter />
      <CheckoutManager />
    </>
  );
}
