import { createServerSideHelpers } from "@trpc/react-query/server";
import { type NextPage } from "next";
import Head from "next/head";

import HomeScreen from "~/components/screens/Home";
import { appRouter } from "~/server/api/root";
import { createInnerTRPCContext } from "~/server/api/trpc";
import { type RouterInputs } from "~/utils/api";
import superjson from 'superjson'

const HomePage: NextPage<{
  input: RouterInputs["shopify"]["collections"]["getAllBasic"];
}> = ({
  input,
}) => {
  return (
    <>
      <Head>
        <title>MSXII Sound Design</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeScreen input={input}/>
    </>
  );
};

export async function getStaticProps() {
  // context: GetStaticPropsContext<undefined>
  const ssg = createServerSideHelpers({
    router: appRouter,
    ctx: createInnerTRPCContext({}),
    transformer: superjson, // optional - adds superjson serialization
  });

  const input: RouterInputs["shopify"]["collections"]["getAllBasic"] = {
    productsFirst: 7,
    collectionsFirst: 50,
  };
  /*
   * Prefetching the `collections.getAllBasic` query here.
   * `prefetchQuery` does not return the result - if you need that, use `fetchQuery` instead.
   */
  await ssg.shopify.collections.getAllBasic.prefetch(input);
  // Make sure to return { props: { trpcState: ssg.dehydrate() } }
  return {
    props: {
      trpcState: ssg.dehydrate(),
      input,
    },
    revalidate: 60,
  };
}

export default HomePage;
