import { createServerSideHelpers } from '@trpc/react-query/server';
import { type NextPage } from 'next';
import Head from 'next/head';

import HomeScreen, { HomeScreenProps } from '~/components/screens/Home';
import { appRouter } from '~/server/api/root';
import { createInnerTRPCContext } from '~/server/api/trpc';
import superjson from 'superjson';
import { api } from '~/utils/api';

const HomePage: NextPage = () => {
	const getAllBasicCollectionsShopify =
		api.shopify.collections.getAllBasic.useQuery();

	const props: HomeScreenProps = getAllBasicCollectionsShopify.isError
		? {
				isError: true,
				error: (getAllBasicCollectionsShopify as { error: { message: string } })
					.error,
				collectionsBasic: null,
				isLoading: false,
				isSuccess: false
		  }
		: getAllBasicCollectionsShopify.isSuccess
		? {
				error: null,
				isError: false,
				collectionsBasic: getAllBasicCollectionsShopify.data,
				isLoading: false,
				isSuccess: true
		  }
		: {
				error: null,
				isError: false,
				collectionsBasic: null,
				isLoading: true,
				isSuccess: false
		  };

	return (
		<>
			<Head>
				<title>MSXII Sound Design</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HomeScreen
				// collectionsBasic={getAllBasicCollectionsShopify.data}
				// isLoading={getAllBasicCollectionsShopify.isLoading}
				{...props}
			/>
		</>
	);
};

export async function getStaticProps() {
	// context: GetStaticPropsContext<undefined>
	const ssg = createServerSideHelpers({
		router: appRouter,
		ctx: await createInnerTRPCContext({ session: null }),
		transformer: superjson // optional - adds superjson serialization
	});
	/*
	 * Prefetching the `products.getAll` query here.
	 * `prefetchQuery` does not return the result - if you need that, use `fetchQuery` instead.
	 */
	await ssg.shopify.collections.getAllBasic.prefetch();

	// Make sure to return { props: { trpcState: ssg.dehydrate() } }
	return {
		props: {
			trpcState: ssg.dehydrate()
		},
		revalidate: 60
	};
}

export default HomePage;
