import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from 'next/font/google';
import { type PropsWithChildren } from "react";
import TRPCProvider from "./components/core/providers/TRPC";

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// authOptions

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      // className={inter.className}
      >
        <TRPCProvider>{props.children}</TRPCProvider>
      </body>
    </html>
  );
}
